### ISSUE TITLE
Side: Trades. Slow chat.

### ISSUE THREAD

**Issue by cpg00** [harshitpunn/tekk#23]
On the chat screen. messaging is slow and long messages take so long to be computed that they do not even get sent.

https://user-images.githubusercontent.com/117692209/227052564-bd7d040a-9af8-4e86-a6b3-e798d1c95bae.mp4

**Comment by cpg00** [comment]
Same problem on Client side.

https://user-images.githubusercontent.com/117692209/227065136-31fe23ca-1b14-4744-9174-3a1db075f8aa.mp4

**Comment by adilsaju** [comment]
use local
