### ISSUE TITLE
Side: Client. Job creation did not go and takes long.

### ISSUE THREAD

**Issue by cpg00** [harshitpunn/tekk#58]
- Hours input allows more than numbers.
- AI generated text for first time takes time.
- After two images added from gallery, third and onward do not appear.
- After completing all inputs. "Create" button did not trigger action.

![IMG_4850](https://user-images.githubusercontent.com/117692209/227063574-f640ff6e-d767-47e1-b521-a1cee1340a99.PNG)

https://user-images.githubusercontent.com/117692209/227064197-b5f74705-3478-438f-a67e-5f5fcff284f2.mp4

**Comment by adilsaju** [comment]
max 2 images now
